title: XiaoMianAO
description: 小棉袄
baseurl: ""
url: "https://xiaomianao.github.io"

lang: zh-CN

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]
